### ISSUE TITLE
change node version

### ISSUE THREAD

**Issue by BilalSohailModi** [serverless/components#1043]
How can I upgrade node version in @serverless/components?
the problem which I'm facing is related to deployment, my code deploys normally from my machine, which is using node 16.x, but when I connect it to ci/cd.
it is failing to deploy since server is using node 12.x, and some of the packages I'm using in the project are incompatible with node 12.x. so I need to add configuration, so that serverless server also use node 16.x to install the packages.

**Comment by medikoo** [comment]
@BilalSohailModi Thanks for interest, still this project is deprecated, please see the main readme

**Comment by BilalSohailModi** [comment]
Okay thanks @medikoo. I didn't read that earlier.
