### ISSUE TITLE
Camel case eventgateway

### ISSUE THREAD

**Issue by DavidWells** [serverless/components#144]
Shouldn't `eventgateway` be `eventGateway`?

https://github.com/serverless/components/blob/master/registry/eventgateway/serverless.yml#L1

If yes, I can update the references

**Comment by DavidWells** [comment]
Same here https://github.com/serverless/components/blob/master/registry/aws-apigateway/serverless.yml#L1

Should be `aws-apiGateway` or `aws-api-gateway`

**Comment by brianneisler** [comment]
@DavidWells good question. So far we've used train case for component types. I think we should continue to stick to this for now. So `eventgateway` would be `event-gateway` and `aws-apigateway` would be `aws-api-gateway`
