### ISSUE TITLE
Aws-dynamodb component does not update

### ISSUE THREAD

**Issue by ebisbe** [serverless/components#193]
Following the instructions in https://serverless.com/blog/how-create-rest-api-serverless-components/ you set the aws-dynamodb component with a GSI. After deploying if you remove the GSI won't update in the following deploys.

**Comment by brianneisler** [comment]
Thanks for the bug report @ebisbe! Will dig in and take a look.

**Comment by ebisbe** [comment]
I was trying to figure out if I could solve it but this component has no tests right now and I'm not confident enough to start them. For what I've been trying it seems that once a deploy is done no further updates on the inputs will make trigger the table update. I think that there are two issues with that component. 

1. https://github.com/serverless/components/blob/master/registry/aws-dynamodb/index.js#L114
If there are no indexes key this if will not update anything. So if you add one and then you delete it removing the indexes key it will not be deleted. So I would update https://github.com/serverless/components/blob/master/registry/aws-dynamodb/index.js#L104 to: 
```
const vIndexes = table.indexes !== undefined ? table.indexes : []
```
2. I think that no further deploys done is cause by this line: 
https://github.com/serverless/components/blob/master/registry/aws-dynamodb/index.js#L245

**Comment by pmuens** [comment]
Thanks for filing this @ebisbe 👍

An upcoming version will fix exactly this. Should be ready to use in a couple of days.
