### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by MagicBlueCH** [serverless/components#225]
# Description
node: v10.0.0
npm: 5.6.0

## Additional Data

{ Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/serverless-components/registry/aws-lambda@0.2.0/serverless.yml'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/serverless-components/registry/aws-lambda@0.2.0/serverless.yml' }

**Comment by moritz31** [comment]
Any solution for this?

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
