### ISSUE TITLE
How to reuse component in another projects?

### ISSUE THREAD

**Issue by azarboon** [serverless/components#237]
Hi.

Thanks for working such a promising project. I've taken a look and have some questions regarding the example project [retail-app](https://github.com/serverless/components/blob/master/examples/retail-app/serverless.yml) :

1.  Can I use e.g. productsDb component in another projects (whether made by Serverless framework or Serverless Components)? If so, how should I refer/use to productsDb? I mean, if I just use its ARN then can I use it inside my other projects?!

2. Can I modify IAM permissions to components? If so, how?﻿

**Comment by eahefnawy** [comment]
@azarboon we've made a complete rewrite of the core and you should be able to reuse components as npm dependencies. You can't however use framework projects as it's completely incompatible. Checkout the readme for more details 🙌
