### ISSUE TITLE
Getting started - slack, docs, dependency resolution, custom components, production

### ISSUE THREAD

**Issue by tommedema** [serverless/components#239]
My main issue with the Serverless Framework is that `.yml` files get out of hand. In theory, serverless components should be able to solve this. I have three questions to which I was unable to find the answer:

1) The readme says that the slack channel is public, but when attempting to join it requires a `@serverless.com` email address.

2) Is there a reason why the serverless docs do not mention anything regarding components at https://serverless.com/framework/docs/getting-started/ ? 

3) Do serverless components use stack sets internally (when using AWS)? How do they orchestrate the order of deletion / creation and resolve dependencies? E.g. if I update component B's version inside component A, and component A depends on component B, and component B fails to upgrade resulting in a rollback, does component A roll back too? Is it possible for two components to be in an invalid state?

In the README I read:

> However the framework ensures that your state file always reflects the correct state of your infrastructure setup (even if something goes wrong during deployment / removal).

How can a local state file work reliably when a team of engineers work together? What if 2 developers deploy at the same time? Will they have different state files? The actual state is on the cloud, not on a local development machine. Do you put the state file in version control?

4) It seems like provisioning is put back in the hands of the developer:

From your README:

```
const deploy = (inputs, context) => {
  // lambda provisioning logic
  const res = doLambdaDeploy()

  // return outputs
  return {
    arn: res.FunctionArn,
    name: res.FunctionName
  }
}
```

However, aren't you re-inventing Terraform here? Also, isn't the point of using Cloudformation that custom provisioning logic isn't necessary? If I want to use AWS, can I still rely on cloudformation to provision my lambda and return the `arn` as an output type?

5) custom components & dependency resolution

if I create 2 components, and one component depends on the other:

```
type: someComponent

components:
  mySpecialThing:
    type: my-custom-component
```

How is someComponent able to resolve the location of `my-custom-component`, if I have not defined where it is? Is there a `package.json` file or something where you specify it as a dependency? Does it read from `node_modules` or similar?

**Comment by eahefnawy** [comment]
This issue is a bit outdated, but we've updated our README which should answer all of these questions.

https://github.com/serverless/components

Closing, but feel free to open it if there's still something that is unclear 😊
