### ISSUE TITLE
AWS CloudFormation Stack component

### ISSUE THREAD

**Issue by brianneisler** [serverless/components#265]
# Description

To help users integrate existing cloudformation stacks into a components deployment, we should implement an aws-cloudformation-stack component.

Here is the AWS js sdk documentation for creating a a CloudFormation Stack https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#createStack-property

## inputTypes
`stackName`: `string` /* required */
`capabilities`: `Array [ CAPABILITY_IAM | CAPABILITY_NAMED_IAM ]`,
`clientRequestToken`: `string`
`disableRollback`: `boolean`
`enableTerminationProtection`: `boolean`
`notificationARNs`: `Array<string>`,
`onFailure`: `enum(DO_NOTHING | ROLLBACK | DELETE)`
`parameters`: `Array<{
    {
      ParameterKey: string,
      ParameterValue: string,
      ResolvedValue: string,
      UsePreviousValue: boolean
    }
    /* more items */
 }>`
`resourceTypes`: `Array<string>`
`roleArn`: `string`
`rollbackConfiguration`: `{
    MonitoringTimeInMinutes: 0,
    RollbackTriggers: [
      {
        Arn: 'STRING_VALUE', /* required */
        Type: 'STRING_VALUE' /* required */
      },
      /* more items */
    ]
}`
`stackPolicyBody`: `string`
`stackPolicyUrl`: `string`
`tags`: `Array<{
    Key: 'STRING_VALUE', /* required */
    Value: 'STRING_VALUE' /* required */
}>,
`templateBody`: `string` 
`templateUrl`: `string`
`timeoutInMinutes`: `integer`

## outputTypes

`stackId`: `string`

**Comment by AaronHarris** [comment]
I already started working on this

**Comment by brianneisler** [comment]
@AaronHarris awesome! thanks for taking this on. Being able to deploy a simple CloudFormation stack through components is a great integration point. One thing to consider as you work on this is how to allow outputs from the CloudFormation stack to be made accessible as outputs in the component. I don't think we need this feature immediately, but something to think about.

**Comment by medampudi** [comment]
any update on this component being integrated into the repository

**Comment by eahefnawy** [comment]
the CloudFormation component is now available here:
https://github.com/serverless-components/aws-cloudformation
