### ISSUE TITLE
Add aws-sqs components

### ISSUE THREAD

**Issue by dilantha111** [serverless/components#307]
# Description
Add an aws-sqs component for creating aws-sqs.
## Inputs
- QueueName 
- DelaySeconds
- MaximumMessageSize
- MessageRetentionPeriod
- ReceiveMessageWaitTimeSeconds
- VisibilityTimeout
- FifoQueue
- ContentBasedDeduplication

## Outputs
- QueueUrl

## Requirements
 

- [x] tests
  

- [x] documentation

  

- [ ] examples

**Comment by dilantha111** [comment]
Hi I would like to work on this feature.

**Comment by brianneisler** [comment]
Hi @dilantha111! Sure, this issue is now assigned to you. Join us on our slack serverless contributors channel if you have any questions about implementation. https://serverless.com/slack. My slack handle is `brian`.
