### ISSUE TITLE
npm run cleanse fails

### ISSUE THREAD

**Issue by dilantha111** [serverless/components#308]
# Description
npm run cleanse fails in windows 10 node v8.11.4 and npm 5.6.0

## Steps followed
- git clone 
- npm install 
- npm run build
Then when running npm run cleanse fails
## debug log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cleanse' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'precleanse', 'cleanse', 'postcleanse' ]
5 info lifecycle serverless-components@0.2.0~precleanse: serverless-components@0.2.0
6 info lifecycle serverless-components@0.2.0~cleanse: serverless-components@0.2.0
7 verbose lifecycle serverless-components@0.2.0~cleanse: unsafe-perm in lifecycle true
8 verbose lifecycle serverless-components@0.2.0~cleanse: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\source\serverless-component\fork\components\node_modules\.bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\DilanthaW\AppData\Local\Programs\Python\Python37-32;C:\Users\DilanthaW\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\PuTTY\;C:\ProgramData\ComposerSetup\bin;C:\gzip;C:\Users\DilanthaW\AppData\Local\Microsoft\WindowsApps;C:\Users\DilanthaW\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\DilanthaW\AppData\Roaming\npm;C:\Users\DilanthaW\AppData\Local\Yarn\bin;C:\xampp\php;C:\xampp\php\ext;C:\Users\DilanthaW\AppData\Roaming\Composer\vendor\bin
9 verbose lifecycle serverless-components@0.2.0~cleanse: CWD: D:\source\serverless-component\fork\components
10 silly lifecycle serverless-components@0.2.0~cleanse: Args: [ '/d /s /c', 'node ./scripts/cleanse.js' ]
11 silly lifecycle serverless-components@0.2.0~cleanse: Returned: code: 1  signal: null
12 info lifecycle serverless-components@0.2.0~cleanse: Failed to exec cleanse script
13 verbose stack Error: serverless-components@0.2.0 cleanse: `node ./scripts/cleanse.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid serverless-components@0.2.0
15 verbose cwd D:\source\serverless-component\fork\components
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "cleanse"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error serverless-components@0.2.0 cleanse: `node ./scripts/cleanse.js`
22 error Exit status 1
23 error Failed at the serverless-components@0.2.0 cleanse script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
