### ISSUE TITLE
 DeleteConflict: Cannot delete a policy attached to entities

### ISSUE THREAD

**Issue by kostjazvankovich** [serverless/components#312]
# Description

I'm getting the following error during removing of a serverless component.

Error: DeleteConflict: Cannot delete a policy attached to entities.
    at remove (/usr/local/lib/node_modules/serverless-components/registry/aws-iam-policy/index.js:60:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

My component consist of the following sub components:

1. aws-im-role
2. aws-im-policy
3. custom component - with was-lambda and rest-api components.

parent's role component is reused in child component.

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
