### ISSUE TITLE
Add support for multiple AWS profiles

### ISSUE THREAD

**Issue by Chan9390** [serverless/components#317]
Currently there's I dont see any way to use components with any AWS profile other than the default one. There's no option like that in serverless (`--aws-profile`) which eases testing in different AWS accounts.

**Comment by eahefnawy** [comment]
Stay tuned for v2 😊 ... this should be much easier!

**Comment by Chan9390** [comment]
@eahefnawy How about golang support for lambda ?

**Comment by eahefnawy** [comment]
@Chan9390 yep we already support that in v1. Here's an example for ya:

https://github.com/serverless/examples/tree/master/aws-golang-simple-http-endpoint

sorry for the late reply. Was on on PTO the past week 😊

**Comment by Chan9390** [comment]
I asked about golang support for serverless components.

**Comment by dschep** [comment]
@Chan9390, components is serverless v2 and under heavy development. It's probably best if you started with go lambdas in v1.

**Comment by eahefnawy** [comment]
@Chan9390 FYI we've made a complete rewrite of the components core, and you can now utilize different accounts by using different `.env` files. More info here:
https://github.com/serverless/components#setting-credentials
