### ISSUE TITLE
static-website component can't cope with existing zones.

### ISSUE THREAD

**Issue by Vad1mo** [serverless/components#347]
# Description
The static-website website component is creating a new hosted zone. However, when there is already a hosted zone then a NS delegation should be created in the parent zone. 

Example:
If there is already an existing domain/hosted zone with the name e.g sandbox.com and there is this setup

```yaml
      hostingDomain: sandbox.com
      aliasDomain: www.sandbox.com
```
A new hosted Zone is created for the alias Domain www.sandbox.com. however there is no connection between the hosted zone `sandbox.com` and `www.sandbox.com` no NS delegation or what so ever.

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
