### ISSUE TITLE
 No Map Schema datatype exists

### ISSUE THREAD

**Issue by gmmurugan** [serverless/components#394]
# Description
No Map datatype support exists here

## Additional Data
https://github.com/serverless/components/tree/master/registry/aws-dynamodb#schema
E.g. 

  {
    "id": 13043945,
    "price": 
    {
      "value": "17.99",
      "currency_code": "USD" 
    }
  }

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
