### ISSUE TITLE
question: roadmap?

### ISSUE THREAD

**Issue by shaunc** [serverless/components#397]
I have been waiting eagerly for serverless/components to mature. The project seems to have lost momentum, however -- fewer commits, fewer downloads, no blog posts.... Do you have a roadmap? Are you still planning to integrate with "traditional" serverless? Are there design issues blocking? Visibility on your intentions would be critical for us to consider adopting it.

Thanks!

**Comment by ac360** [comment]
@shaunc Thanks for raising this.  We learned a lot from the initial project.  Now, we're doing more...

For the past few months, we've been working on a big update to Serverless Components that is simpler, faster and more powerful.  We will be pushing this update into this Github repo on Tuesday, March 26th.  

We're all very excited about it and we cannot wait to get your feedback.  Thanks for hanging in there.  We hope to reward your patience.

**Comment by shaunc** [comment]
Wonderful -- will be looking forward to the new version!

**Comment by ac360** [comment]
@shaunc Everything is being updated now.  Let us know what you think :)

**Comment by shaunc** [comment]
Great! Will be studying ....
