### ISSUE TITLE
Modify Ramda

### ISSUE THREAD

**Issue by ac360** [serverless/components#399]
I know you guys love Ramda, but I think it goes directly against the goal of having an accessible codebase.

Ramda is a functional abstraction over vanilla javascript.  When encountering it, it is like seeing another programming language, especially given how many minor functions are scattered everywhere.  It requires knowing Ramda or keeping their docs open 24/7 just to understand our codebase.

**Comment by eahefnawy** [comment]
Done. But this is something we should be striving for moving forward.
