### ISSUE TITLE
Serverless Variables - Improve Referencing Current Component Attributes

### ISSUE THREAD

**Issue by ac360** [serverless/components#40]
**Problem**

I tried using the AWS Lambda Component, however it currently hardcodes the current working directory as the folder to be packaged for the function, which is a bad practice.  This forces the Lambda Component to package up EVERYTHING in my top-level Component, whether it's related to my function or not, resulting in a bloated, slow and potentially non-working Lambda Function.  If users can't point to a specific directory where their Lambda code exists, then the Lambda Component isn't very usable.

**Problem Example**

-  Component A – _Top-level component_
   - Component B – _Lambda code located here_
       - Component C – _Lambda component_

I need to pass the Lambda Code in Component B via an input to Component C, the Lambda Component.  Currently, the current working directory is hardcoded as the path of the Lambda code in the Lambda Component, meaning everything in Component A will be packaged into the function.  This misses the Lambda code completely and instead fills it with unrelated files from Component A.

**Potential Solution**

There needs to be a way to pass in relative paths.  If Serverless Variables had some built-in helpers, this would solve the problem well.  Users can use them to address the above problem, like this:

**Potential Solution Example**

Component B

```yaml
components:
  function:
    type: aws-lambda
    inputs:
      handler: index.code
      handlerRoot:  ${self.path}/code
```

`${self}` could be expanded upon to offer info about the current component, in a consistent way:

- `${self.path}` - Points to the path of the current component
- `${self.inputs.foo}` – Reference an input of the current component
- `${self.name}` – Reference the name of the current component
- `${self.version}` – Reference the version of the current component

**Comment by brianneisler** [comment]
`${self..path}` has been implemented. 

I think we should try to stay consistent with the property names though. `${self.name}` should really be `${self.type}` (if i'm understanding the use case).

`${self.version}` will be implemented once we add versioning to components. 

I don't agree that `${self.inputs}`  should be a thing. I think of `inputs` in the same way as constructor arguments of a class. It is up to the component as to whether it stores them on properties. Given this, i think it makes sense for inputs to remain `${inputs.foo}`.
