### ISSUE TITLE
Unable to deploy the AwsApiGateway Component

### ISSUE THREAD

**Issue by ac360** [serverless/components#414]
<img width="1468" alt="Screen Shot 2019-03-26 at 2 18 02 PM" src="https://user-images.githubusercontent.com/2752551/55034141-03622180-4fd2-11e9-940e-70060e98bcd1.png">

I can't tell if this is a core issue or something else.  It looks like it's trying to load a Component class name as the npm module.

cc @pmuens

**Comment by pmuens** [comment]
This should've been fixed. Closing...
