### ISSUE TITLE
Declarative State Breaks Conventions

### ISSUE THREAD

**Issue by ac360** [serverless/components#420]
It looks like the state files for declarative use do 2 things different from the conventions we've set:

* It uses `declarative` as the name, instead of the `name` property.
* It creates multiple state files for each dependency.
* it uses it's own system for saving and loading state, not the Component's system.

Why can't this just use the state system we have already w/ the conventions we have?

One state file, titled after the `name` property, saved via `this.save`

When we break architectural/conceptual consistency this early in a project, it sets a course for a much bigger mess later.

cc @pmuens

**Comment by pmuens** [comment]
I agree with this and already shared my thought in https://github.com/serverless/components/issues/407.

Generally speaking I need the name of the component to re-load it and populate it with the state information. The current state files don't contain the name of the component which is used, making it impossible to load the component and set the corresponding inputs.

**Comment by pmuens** [comment]
Refactored the implementation via https://github.com/serverless/components/commit/ce68db0db311e71bee40308ad00044d9e843f926
