### ISSUE TITLE
Generate .gitignore files

### ISSUE THREAD

**Issue by dschep** [serverless/components#423]
Since components creates directories such as `.serverless` and `node_modules`, it should generate an appropriate `.gitignore` file when you start a new project.

**Comment by eahefnawy** [comment]
makes total sense 👍

**Comment by eahefnawy** [comment]
@dschep do you think that should be only for the component template? or any template?

**Comment by dschep** [comment]
Any template that generates files/directories that shouldn't be committed to git should have a `.gitignore` containing those files/directories. So... probably all templates should at least have a `.gitignore` that ignores `.serverless` and any JS based ones should also ignore `.serverless`

**Comment by dschep** [comment]
Actually. it should always generate one. Should always ignore `.env` by default for security reasons

**Comment by eahefnawy** [comment]
just added that. Thanks @dschep
