### ISSUE TITLE
Can't deploy without using [sudo]

### ISSUE THREAD

**Issue by pdaryani** [serverless/components#425]
Deploying my application via components requires the use of sudo `sudo components` otherwise I get the following error:

```
my-api › error:
  { Error: EACCES: permission denied, open '/Users/xxx/xxx/xxx/xxx/.serverless/dev.my-api.myLambda.AwsIamRole.json'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/xxx/xxx/xxx/xxx/.serverless/dev.my-api.myLambda.AwsIamRole.json' }


  3s › dev › my-api › Error: EACCES: permission denied, open '/Users/xxx/xxx/xxx/xxx/.serverless/dev.my-api.myLambda.AwsIamRole.json'
```

Would be great if I could deploy without using `sudo` every time :)

**Comment by eahefnawy** [comment]
I'm curious why you need sudo 🤔 ... @pmuens @ac360 does any of you require sudo?

**Comment by pdaryani** [comment]
@eahefnawy umm just noticed that I had a similar permission issue with another package, probably something to do with my specific setup

will look into this again later today and close this ticket if above is the case :)

**Comment by eahefnawy** [comment]
@pdaryani will close this. Feel free to reopen if you still think it's an issue with the core.
