### ISSUE TITLE
Specific Component READMEs/Docs should contain Access Key information for providers

### ISSUE THREAD

**Issue by ac360** [serverless/components#427]
Currently, component readmes/docs don't contain access key info.  This is a big missing step in credentials.

**Comment by eahefnawy** [comment]
I've actually included the `.env` files in the template directory, but I forgot that they're .gitignored and .npmignored. We probably shouldn't include them in the repo nor the npm package.

So I've updated the core README as well as all components readme to include information on setting up credentials.
