### ISSUE TITLE
Don't export utilities in the top-level namespace

### ISSUE THREAD

**Issue by ac360** [serverless/components#430]
We're currently exporting utilities in the top-level namespace, which seems like an implementation that will result in collisions.

I think we should consider keeping them under a utilities object.

```javacript

const { Component, utils } = require('@serverless/components')

```

**Comment by eahefnawy** [comment]
I've exported `utils` as you described and published. However I kept the utils at the root level too for now. Didn't want to break things doing a big patch of renaming.

Moving forward, we should export utils as described above.

**Comment by eahefnawy** [comment]
This has been done
