### ISSUE TITLE
Running `serverless` with components does not work

### ISSUE THREAD

**Issue by mnapoli** [serverless/components#462]
After creating a test `serverless.yml` with:

```yaml
name: test

foo:
    component: '@serverless/website'
```

And running:

```
serverless
```

I get the error:

```
  Serverless Error ---------------------------------------

  "service" property is missing in serverless.yml

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              11.14.0
     Serverless Version:        1.49.0
     Enterprise Plugin Version: 1.3.6
     Platform SDK Version:      2.1.0
```

I did update to the latest `serverless` version.

Am I missing something? I went through the docs as much as I could but cannot figure this out.

**Comment by ac360** [comment]
Thanks @mnapoli.  Looking into it right now..

**Comment by eahefnawy** [comment]
@mnapoli thanks for reporting. That is really odd. Does your yaml file contain anything else? Or just that? My theory is that for some reason the framework thinks that you're running a framework project rather than a components project.

**Comment by mnapoli** [comment]
Ohh I found out why: I had a `serverless.js` in the same directory. I wanted to try to build a component.

My bad!

**Comment by ac360** [comment]
@mnapoli We're really excited in seeing what you come up w/ (related to Bref and all things serverless PHP).  Please don't hesitate to reach out to @eahefnawy with any questions or needs. Simple PHP serverless outcomes is what Components is designed to offer.

**Comment by mnapoli** [comment]
@ac360 awesome thanks! And I'll be sure to keep you updated if I make any progress.

By the way I just stumbled upon this in the README:

> A directory cannot contain both a serverless.yml and a serverless.js.

oops 😅

**Comment by eahefnawy** [comment]
haha yep. @mnapoli yep. The order of operation is:

1. JS file if found
2. YAML file if found
3. JSON file if found

all assuming they're **valid** components file. So I'm guessing your `serverless.js` file was not a valid component file? is that correct?

**Comment by mnapoli** [comment]
Yes very probably! When I got it to stop erroring I had to make another change to make my custom component (now in another directory) work: https://github.com/serverless/components/pull/464 (so I assume it wasn't working before)

🤔 and to be sure I understand: I can use a `serverless.js` file in place of a `serverless.yml` file to configure and deploy an application?

If that's correct, is the inverse true: can I write a component (mostly composed of other components) via a `serverless.yml` file?

**Comment by eahefnawy** [comment]
@mnapoli yeah if the component class is not exported, then the core has no idea that it's a component, so it moves on to the framework logic.

As for writing components via a YAML file, you can compose components together with a YAML file and deploy that, but that does not produce a new component (ie. you cannot publish it to npm for people to use, it doesn't have a component name...etc). It's more like a template/collection of components.

Overall, if your setup/composition is simple, we recommend using the YAML file, if it's complicated and requires a real programming environment, we recommend a JS file, which would also produce a higher level component if you'd like to.

**Comment by ac360** [comment]
@mnapoli I just added that to the docs after seeing this issue ;)

**Comment by mnapoli** [comment]
:+1: a bit like AWS CDK I guess. Makes sense, thanks!

**Comment by eahefnawy** [comment]
@mnapoli do you think it would be worthwhile to be able to publish a component that is just a YAML file composition? (with backend/frontend code if applicable)

**Comment by mnapoli** [comment]
@eahefnawy I'm not really sure, maybe not since the target audience for writing components is probably not the same as the audience that will build applications. I need to play a little more with all this to get a better idea I think 😄
