### ISSUE TITLE
layers

### ISSUE THREAD

**Issue by patie** [serverless/components#465]
hi, can you add example/template for lamba layers please? thanks

**Comment by pmuens** [comment]
Hey @patie thanks for opening.

Sure thing. Here's the Lambda layer component --> https://github.com/serverless-components/aws-lambda-layer

You can find more components in our components org: https://github.com/serverless-components

**Comment by patie** [comment]
thank you, and its possible somehow using layers in backend or fullstack component? probably not right?

**Comment by eahefnawy** [comment]
@patie the backend component already uses the layers component to package your dependencies if they have changed. This makes deployment tenfold faster if you haven’t changed your dependencies (probably 90% of dev time).

You may also deploy your own layer as well in the same yaml file of course

**Comment by patie** [comment]
any news?

**Comment by eahefnawy** [comment]
Sorry @patie we didn't have time to implement this. PR is welcome though. If we add support in the lambda component, should be easy to add support for the backend component too. Here's the repo if someone is interested in opening a PR 😊 

https://github.com/serverless-components/aws-lambda
