### ISSUE TITLE
website template throwing "service" property is missing in serverless.yml

### ISSUE THREAD

**Issue by joshstrange** [serverless/components#467]
# Description
Running `sls` or `sls deploy` results in:

````
  Serverless Error ---------------------------------------

  "service" property is missing in serverless.yml

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           10.16.1
     Serverless Version:     1.46.1

````

## Additional Data

I created this project by running the following commands:

````
serverless create --template-url https://github.com/serverless/components/tree/master/templates/website
cd website
npm install
sls deploy
````

I've tried nesting "name" under "service" in the yaml file but it throws the same error. I was trying to get this to work with my existing angular project but it was having the same issue so I tried to use the template to compare what was different but the template isn't working either.

**Comment by joshstrange** [comment]
Also I did see #462 but that's not my issue (I have no other files named serverless.*):

````
~/g/j/website ❯❯❯ ls -la                                                                                                                                                                                                      ✘ 1
total 600
drwxr-xr-x   13 josh  staff     416 Aug  7 11:13 .
drwxr-xr-x   56 josh  staff    1792 Aug  7 11:12 ..
-rw-r--r--    1 josh  staff      25 Aug  7 11:12 .gitignore
drwxr-xr-x    6 josh  staff     192 Aug  7 11:18 .idea
drwxr-xr-x    3 josh  staff      96 Aug  7 11:13 .serverless
-rw-r--r--    1 josh  staff    2403 Aug  7 11:12 README.md
-rw-r--r--    1 josh  staff    8552 Aug  7 11:12 favicon.ico
-rw-r--r--    1 josh  staff     480 Aug  7 11:12 index.html
drwxr-xr-x  551 josh  staff   17632 Aug  7 11:12 node_modules
-rw-r--r--    1 josh  staff  273973 Aug  7 11:12 package-lock.json
-rw-r--r--    1 josh  staff     837 Aug  7 11:12 package.json
-rw-r--r--    1 josh  staff     271 Aug  7 11:12 serverless.yml
drwxr-xr-x    7 josh  staff     224 Aug  7 11:12 src

````

**Comment by ac360** [comment]
Hi @joshstrange,

Could you try upgrading to the latest version of serverless framework?  The version you are using might not have Components available.  We are currently on version 1.49.

Once you upgrade, only use the `serverless` command to deploy.

**Comment by ac360** [comment]
Also, you might want to remove your `.serverless` folder in your current working directory after you upgrade and before you deploy.

Let us know how it goes.  We're standing by!

**Comment by joshstrange** [comment]
Well I got further (still didn't make progress on my existing codebase but 1 step at a time). It looked like it was going to deploy then I got:

````


  error:
  { AccessDenied: Access Denied
    at Request.extractError (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/josh/.serverless/components/registry/npm/@serverless/website@3.0.6/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2019-08-07T20:06:48.217Z,
  requestId: '38C04E76DDFC242D',
  extendedRequestId:
   '0IEOvWfxV6My/qeWdOWzMeUTQL79dhMrUS2d2o+so1J2epw+zTrxd9z4b/21RpoNcvRqBDH6A6E=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 91.02477840786372 }

  3s › website › AccessDenied: Access Denied

````

My guess is my serverless-agent IAM user doesn't have the needed permissions to do something in S3 but I have the following permissions:

````
                "s3:CreateBucket",
                "s3:DeleteBucket",
                "s3:DeleteBucketPolicy",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:GetObject",
                "s3:GetObjectVersion",
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:PutBucketNotification",
                "s3:PutBucketPolicy",
                "s3:PutBucketTagging",
                "s3:PutBucketWebsite",
                "s3:PutEncryptionConfiguration",
                "s3:PutObject",
````

**Comment by joshstrange** [comment]
Wait a minute... does serverless just keep walking up directories looking for a ".serverless" folder? Or do I need to kill my `~/.serverless` folder between updates?

**Comment by ac360** [comment]
Hi @joshstrange, 

Sorry about this.  

The 403 error indicates either your `serverless-agent` is missing the IAM permissions needed, or the Framework simply can't find your credentials.  Be sure to add all AWS S3 bucket permissions to your IAM policy.  Additionally, ensure your credentials are available to the Serverless Framework.  [Guidance is provided here](https://github.com/serverless/components#credentials).

The Framework does not crawl directories to find a `.serverless` dir.  It looks only in the current working directory.  I was suggesting to clear it last time because you were using an older version of the Framework and the `.serverless` directory contained irrelevant information because of that.

As for next steps, I suggest to check permissions and credentials.  Try to run `serverless remove`.  Then run `serverless` again.  If that doesn't work, then I recommend deleting the `.serverless` and running `serverless` again.

**Comment by eahefnawy** [comment]
@joshstrange if you're passing the `domain` input, you're gonna need extra access to CloudFront, Route53 & ACM. If not, I've looked into the codebase and here are the AWS S3 methods both the `website` and its child `aws-s3` component use:

```js
putBucketWebsite()
putBucketCors()
putBucketPolicy()
headBucket()
createBucket()
upload()
listObjects()
deleteObject()
putBucketAccelerateConfiguration()
deleteBucket()

// the following is required from the external s3-upload-stream package
createMultipartUpload() 
completeMultipartUpload()
uploadPart()
```

I think this is all, and I see that you're missing some stuff in the list you've shared. If you could try to have access to those and let us know, it would be great. If it still didn't work, maybe you can enable complete access to S3 (if possible) just to make sure that's the issue then we can figure out what's missing.

**Comment by joshstrange** [comment]
@eahefnawy Perfect timing, I was just ripping open the aws/S3 npm package, I'll try adding those permissions to my IAM. I already commented out the domain part (but I think I got that working when I setup my backend to use a custom domain) for now to reduce the complexity. I'll report back once I've added the permissions and tried again.

**Comment by eahefnawy** [comment]
Sounds good! We're waiting... 😊

**Comment by joshstrange** [comment]
Ok it looks like I was missing the following:

````
putBucketCors()
headBucket()
putBucketAccelerateConfiguration()
````

I added those to my policy and now the template is correctly deploying! The rest of the permission I had either already set or couldn't find the IAM permission tied to the names above (I assume because a different IAM permission already covers it. Now to get my existing angular app to deploy (it was still throwing the service property error last time I tried)...

**Comment by joshstrange** [comment]
*sigh* Ok, still have the same issue on my existing project:

````
  Serverless Error ---------------------------------------

  "service" property is missing in serverless.yml

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.1
     Serverless Version:        1.49.0
     Enterprise Plugin Version: 1.3.8
     Platform SDK Version:      2.1.0
````

There is no `.serverless` folder in my project's folder, no npm packages installed, as you can see my version of serverless is up-to-date. I even deleted my `~/.serverless` folder to be sure nothing was hanging around. Is there anything else I can try deleting? I used the EXACT same `serverless.yml` file from the template.

**Comment by eahefnawy** [comment]
could you share your dir structure?

**Comment by joshstrange** [comment]
Sure, not sure how best to "Export" that, here is the top level:

````
drwxr-xr-x   21 josh  staff     672 Aug  8 09:00 .
drwxr-xr-x   56 josh  staff    1792 Aug  7 11:12 ..
-rw-r--r--    1 josh  staff     244 Aug  4 16:16 .editorconfig
drwxr-xr-x   12 josh  staff     384 Aug  7 11:00 .git
-rw-r--r--    1 josh  staff     631 Aug  4 16:12 .gitignore
drwxr-xr-x    9 josh  staff     288 Aug  8 09:00 .idea
-rw-r--r--    1 josh  staff    1028 Aug  4 16:12 README.md
-rw-r--r--    1 josh  staff    3904 Aug  4 16:14 angular.json
-rw-r--r--    1 josh  staff     429 Aug  4 16:12 browserslist
drwxr-xr-x    3 josh  staff      96 Aug  7 11:01 dist
drwxr-xr-x    5 josh  staff     160 Aug  4 16:12 e2e
-rw-r--r--    1 josh  staff    1025 Aug  4 16:12 karma.conf.js
drwxr-xr-x  773 josh  staff   24736 Aug  4 16:14 node_modules
-rw-r--r--    1 josh  staff  426850 Aug  4 16:14 package-lock.json
-rw-r--r--    1 josh  staff    1377 Aug  4 16:14 package.json
-rw-r--r--    1 josh  staff     268 Aug  8 09:00 serverless.yml
drwxr-xr-x   11 josh  staff     352 Aug  4 16:17 src
-rw-r--r--    1 josh  staff     270 Aug  4 16:12 tsconfig.app.json
-rw-r--r--    1 josh  staff     543 Aug  4 16:12 tsconfig.json
-rw-r--r--    1 josh  staff     270 Aug  4 16:12 tsconfig.spec.json
-rw-r--r--    1 josh  staff    1889 Aug  4 16:15 tslint.json
````

**Comment by eahefnawy** [comment]
looks good 🤔 ... are you running `sls deploy` or just `sls`?

**Comment by joshstrange** [comment]
I used to run `sls deploy` but as per @ac360's comment above I just use `sls` now (I also tried `serverless` just to be sure).

**Comment by eahefnawy** [comment]
hmmm that's really odd, the framework seems to think you're running a framework project. Do you confirm that this is how your yaml file looks like?

```yml
name: website

website:
  component: '@serverless/website'
  inputs:
    code:
      src: dist
      hook: npm run build
```

**Comment by joshstrange** [comment]
@eahefnawy Yes, I've tried with that exact yaml file. My current one looks like this:
````
name: website

website:
	component: '@serverless/website'
	inputs:
		code:
			src: dist/food-week-web
			hook: npm run build
		env:
			foo: bar
		# domain: www.serverless-fullstack.com # Register a custom domain on AWS Route 53 to enable this, AWS Cloudfront and SSL.
````


Also I added a console.log in Service.js (from serverless) to see it's loading the correct file:
````
console.log(serviceFilename, serverlessFileParam); // Added inside loadServiceFileParam
````
Output: 
````
/Users/josh/git/joshstrange/food-week-web/serverless.yml
{ name: 'website',
  website: null,
  component: '@serverless/website',
  inputs: null,
  code: null,
  src: 'dist/food-week-web',
  hook: 'npm run build',
  env: null,
  foo: 'bar' }

````

From this output it's not surprising to me that it would fail as just a few lines later it does the following check:

````
if (!serverlessFile.service) {
      throw new ServerlessError(`"service" property is missing in ${this.serviceFilename}`);
    }
````

**Comment by eahefnawy** [comment]
I'm feeling there might be an issue with your yaml indentation. The code snippet you provided shouldn't be reached if the components project is detected. Could you make sure you're using correct indentation for the yaml file? (ie. two spaces)

**Comment by joshstrange** [comment]
.... I figured it out, it's spaces/tabs in my yaml

**Comment by eahefnawy** [comment]
ah! cool. Is it deployed? 😄

**Comment by eahefnawy** [comment]
FYI if you don't like yaml/indentation, you can always use `serverless.json` 😉

**Comment by joshstrange** [comment]
Haha, I guess we commented at the same time, yep, I'm an idiot, I guess my editor switched it from spaces -> tabs when I pasted it in 🙄. I'm sorry for wasting your time, but at least my IAM permissions issue was "real" 😆. THANK YOU, It's deploying now! And I will be looking into using serverless.json, I'm not a huge fan of yaml anyways as I use it on VERY few things.

**Comment by eahefnawy** [comment]
Great! Remember if you use a domain:

1. It must be already purchased in Route53
2. You'll need extra access in your IAM

**Comment by joshstrange** [comment]
@eahefnawy Yes I am playing the wack-a-permission game right now with that, I'll post back here my full IAM permission list for S3/Route53/anything-else-I-think-I-needs once I've got it working. I know my serverless-agent user has some of what it needs as I had to add stuff for my backend to use a custom domain.

Just a suggestion (which I'm sure is not new/novel) but it would be really nice if parts of serverless (maybe start with components?) could expose a list of permissions they need and it could check ahead of time and error out with a "Please add the following IAM permissions to your policy".

I release AWS != Serverless so maybe an array per provider of needed permissions or possibly an abstraction of permissions mapped to each provider (but that sounds a lot harder as I'm sure permissions do not map 1-to-1 in many cases).

**Comment by joshstrange** [comment]
Ok, I'm closer...

````
~/g/j/food-week-web ❯❯❯ SLS_DEBUG=* sls                                                                                                                                                                                       

  website:
    url:    http://REMOVED.s3-website-us-east-1.amazonaws.com
    env:
      foo: bar2
    domain: https://foodweek.app

  34s › website › done

````

What is very odd is my domain is `www.foodweek.app` because I was getting a different error when I tried just `foodweek.app` in the yaml. I assumed serverless didn't like the root domain but even though it completed and the s3 URL works neither the `www.foodweek.app` nor the `foodweek.app` url work.

For the record here is my full policy, sorry it's not grouped by service, aws shuffled them at some point on me:

````
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:AttachInternetGateway",
                "iam:PutRolePolicy",
                "cloudformation:CreateChangeSet",
                "dynamodb:DeleteTable",
                "cloudfront:CreateInvalidation",
                "route53:ListHostedZonesByName",
                "ec2:DeleteRouteTable",
                "ec2:CreateInternetGateway",
                "cloudformation:UpdateStack",
                "sns:Subscribe",
                "events:RemoveTargets",
                "ec2:DeleteInternetGateway",
                "logs:FilterLogEvents",
                "s3:DeleteObject",
                "iam:GetRole",
                "events:DescribeRule",
                "sns:ListSubscriptionsByTopic",
                "apigateway:*",
                "iot:DisableTopicRule",
                "ec2:CreateTags",
                "sns:CreateTopic",
                "iam:DeleteRole",
                "s3:DeleteBucketPolicy",
                "iot:CreateTopicRule",
                "dynamodb:CreateTable",
                "s3:PutObject",
                "s3:PutBucketNotification",
                "cloudformation:DeleteStack",
                "logs:PutSubscriptionFilter",
                "apigateway:POST",
                "ec2:CreateSubnet",
                "cloudformation:ValidateTemplate",
                "ec2:DeleteNetworkAclEntry",
                "iot:ReplaceTopicRule",
                "cloudformation:CreateUploadBucket",
                "cloudformation:CancelUpdateStack",
                "events:PutRule",
                "ec2:CreateVpc",
                "sns:ListTopics",
                "cloudformation:UpdateTerminationProtection",
                "s3:ListBucket",
                "cloudformation:EstimateTemplateCost",
                "apigateway:DELETE",
                "iam:PassRole",
                "iot:DeleteTopicRule",
                "cloudformation:GET",
                "s3:PutBucketTagging",
                "iam:DeleteRolePolicy",
                "cloudfront:UpdateDistribution",
                "s3:DeleteBucket",
                "ec2:DeleteNetworkAcl",
                "states:CreateStateMachine",
                "sns:GetTopicAttributes",
                "route53:ListHostedZones",
                "kinesis:DescribeStream",
                "sns:ListSubscriptions",
                "cloudformation:Describe*",
                "events:DeleteRule",
                "ec2:Describe*",
                "iam:CreateServiceLinkedRole",
                "s3:ListAllMyBuckets",
                "s3:PutBucketWebsite",
                "s3:GetObjectVersion",
                "cloudformation:Get*",
                "ec2:DeleteSubnet",
                "route53:GetHostedZone",
                "states:DeleteStateMachine",
                "iam:CreateRole",
                "sns:Unsubscribe",
                "s3:CreateBucket",
                "iam:AttachRolePolicy",
                "cloudformation:ContinueUpdateRollback",
                "iam:DetachRolePolicy",
                "events:ListRuleNamesByTarget",
                "dynamodb:DescribeTable",
                "acm:RequestCertificate",
                "logs:GetLogEvents",
                "route53:ListResourceRecordSets",
                "events:ListRules",
                "apigateway:GET",
                "cloudformation:List*",
                "s3:HeadBucket",
                "cloudformation:ExecuteChangeSet",
                "events:ListTargetsByRule",
                "route53:ChangeResourceRecordSets",
                "kinesis:CreateStream",
                "ec2:CreateRouteTable",
                "sns:GetSubscriptionAttributes",
                "ec2:DetachInternetGateway",
                "s3:PutBucketCORS",
                "logs:CreateLogGroup",
                "s3:GetObject",
                "kinesis:DeleteStream",
                "acm:DescribeCertificate",
                "iot:EnableTopicRule",
                "ec2:DeleteVpc",
                "s3:PutAccelerateConfiguration",
                "sns:DeleteTopic",
                "logs:DescribeLogStreams",
                "s3:DeleteObjectVersion",
                "sns:SetTopicAttributes",
                "s3:PutEncryptionConfiguration",
                "ec2:CreateSecurityGroup",
                "apigateway:PATCH",
                "ec2:CreateNetworkAcl",
                "acm:ListCertificates",
                "ec2:ModifyVpcAttribute",
                "logs:DescribeLogGroups",
                "logs:DeleteLogGroup",
                "cloudfront:CreateDistribution",
                "cloudformation:PreviewStackUpdate",
                "events:PutTargets",
                "sns:SetSubscriptionAttributes",
                "cloudformation:CreateStack",
                "ec2:DeleteSecurityGroup",
                "cloudfront:ListDistributions",
                "lambda:*",
                "s3:PutBucketPolicy",
                "ec2:CreateNetworkAclEntry"
            ],
            "Resource": "*"
        }
    ]
}
````

**Comment by joshstrange** [comment]
Interestingly Route53 DOES have a record for `www` pointed at a cloudfront instance, it just doesn't work. For the record the domain IS working for my backend (using serverless-domain-manager)

**Comment by joshstrange** [comment]
Wait, I may be a little off, I just pulled up cloudfront in the console and it's "In Progress" of deploying, I may have jumped the gun...

**Comment by eahefnawy** [comment]
@joshstrange yeah it takes a while 😊

**Comment by eahefnawy** [comment]
> Just a suggestion (which I'm sure is not new/novel) but it would be really nice if parts of serverless (maybe start with components?) could expose a list of permissions they need and it could check ahead of time and error out with a "Please add the following IAM permissions to your policy".

Thanks for your suggestions @joshstrange ... we are definitely on the same page here. We are planning a permissions component that would make this a lot easier. You should NOT have to do this manually, you should just deploy and enjoy some Pinacolada in some far away beach 🍹

**Comment by joshstrange** [comment]
@eahefnawy Yeah who would have thought, deploying something to a massive CDN like cloudfront might take more than a few seconds 😆...  I think once it's done all my issues will be solved, thank you for the extensive hand-holding! I am very close to my dream of serverless infrastructure for my front and backend and it's super exciting.

**Comment by eahefnawy** [comment]
You're most welcome 😊 ... please do let me know if you face any further issues. And if you're not there already, feel free to join our Slack [via this link](https://serverless-contrib.slack.com/join/shared_invite/enQtNDI4MjM3MTIwMTgzLTE3Y2RkOTY1YTY1MTE0ZjA0YTBhYjA2NzNiMGUwODNlYWFjNjE3YTE1OGFjZjFiNmE1NTgzM2NjYzc5ZTNhM2Q)so that you can have a direct contact with me in case of serverless emergency! 😄

**Comment by ac360** [comment]
@joshstrange Here is the experience you _should_ have:  https://www.youtube.com/watch?v=ts26BVuX3j0

Hopefully this helps :)

**Comment by joshstrange** [comment]
@ac360 Great video! Just a note (which you might know) you don't have to buy the domain on AWS to make it work. I bought mine on namecheap and just set it up in Route53 (pointed NS from namecheap to Route53's).

**Comment by eahefnawy** [comment]
@joshstrange thanks for sharing this critical info. Do you might sharing a bit more info? (ie. the steps you've taken at least on the AWS side, since they're probably different depending on the registrar)

We'd love to add it to the docs 🙌

**Comment by joshstrange** [comment]
@eahefnawy Now that I've been put on the spot I'm sure I'll miss one of my steps but I'm pretty sure this is all I did:

1. Register domain on 3rd party registrar (I used namecheap)
2. In Route53 create new hosted zone (It just asks for the domain name and the type, you want "Publicly hosted zone"
3. After the hosted zone is created it will show you the DNS entries which include the nameservers (type: NS)
4. In your domain registrar edit the nameservers to be the 4 nameservers listed in AWS
5. Wait up to 24 hours for DNS to propagate (I think I waited a day, not on purpose, but I had set it up a good day before I went to use it).

-- Not sure if you need to do the next steps or not, I don't think you need it for `@serverless/website`, I think it WAS required for me to use the `serverless-domain-manager` plugin I am using on my backend

6. In AWS Certificate Manager request a certificate of `*.yourdomain.com` then use the ARN in your serverless config:

````
custom:
  customDomain:
    domainName: 'api.yourdomain.com'
    basepath: ''
    certificateArn: 'arn:aws:acm:us-east-1:XXXXXXXXXXX:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX'
    createRoute53Record: true
```` 


Due to the fact I see 2 certificates in my AWS and I only created 1 of them I think you can skip step 6 but I'll leave it here just for anyone that stumbles across this who is using `serverless-domain-manager`

**Comment by eahefnawy** [comment]
Thanks for sharing @joshstrange ... Yeah that makes total sense. The certificate stuff is auto created for you if you use a domain for the `website` or `backend` components. So yeah, this step is not required.

So basically all you need to do is just create a new Public Hosted Zone for your domain, and point to the name servers that AWS provides for you from your domain registrar. Then just wait.

Sounds good! Will add that to the docs👌

**Comment by morgler** [comment]
I have the same problem with "service" property missing, but probably a different cause:

My simple `serverless.yml` for the "website" component worked fine as along as it was in a file named exactly `serverless.yml`. 

```
component: website-morgler
name: gixtra-frontend
org: morgler
app: gixtra

inputs:
  bucketName: gixtra-frontend-${stage}
  src: ./dist/spa
  region: eu-central-1
```
_(temporarily using my own fork of the component to fix some things)_

Once I put the **same** content into a file named `serverless-website.yml` and then try to do `sls --config serverless-website.yml`, I get the error about the missing "service" property.

Why is this different, if nothing but the config file name changed?

**Comment by eahefnawy** [comment]
@morgler we don't support `sls --config` in components. The file must be `serverless.yml`

**Comment by morgler** [comment]
Ok, I can live with that.

It was just a little unexpected that calling `sls --config …` or `sls --stage …` invokes a totally different workflow than `sls`.

Btw: If anyone needs to call deploy for a component with `--stage` parameter (e.g. on a CI server), you can just use `SERVERLESS_STAGE=… sls`.

**Comment by eahefnawy** [comment]
@morgler what determines the flow is actually the `serverless.yml` file. Depending on its structure (and even existence), the CLI figures out whether to load framework or components. The default flow is the framework flow, so if the `serverless.yml` file does not exist, it'll just go with that.

**Comment by morgler** [comment]
I see. So we have to find work-arounds for the things we would normally do with params, like setting the `stage`. I now have the problem that I try to set the `stage` like this:

`SERVERLESS_STAGE=prod sls`

However, inside `serverless.yml` the `{stage}` variable is still `dev`. Am I using the correct way of setting the `stage` for the component?

**Comment by eahefnawy** [comment]
Option C is correct. You can also specify the stage as a CLI flag with `sls deploy --stage prod`. Default is `dev`.

```
inputs:
  bucketName: myapp-${stage}
```

**Comment by morgler** [comment]
I tried option C, but I always get `dev` as the value for `stage`, even with `SERVERLESS_STAGE=prod sls`.  The same goes for `sls deploy --stage qa`– it deploys to `dev`.

**Comment by eahefnawy** [comment]
Hmm well, that can't be right. We are setting it right here:
https://github.com/serverless/components/blob/master/src/cli/commands/utils.js#L120

Are you running the latest version of the framework?

**Comment by morgler** [comment]
That was it! I was still on 2.22.3. After upgrading to 2.29.2 it honors the `--stage` param. Thanks!

**Comment by eahefnawy** [comment]
We are following semver. So things should be ok, but if they found unexpected breaking changes, then it's on us and please let us know. 😊

**Comment by morgler** [comment]
They're still on v1 :P

**Comment by Amber-Williams** [comment]
Hi I'm having this issue as well while trying to deploy with `serverless` and `sls` I had it working a few weeks ago with my same `serverless.yml`. I have been trying different versions, removing the `.serverless` with no relief

```
  Serverless Error ---------------------------------------
 
     "service" property is missing in serverless.yml
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       12.4.0
     Serverless Version: 1.6.1
```

Here's my serverless config
```
org: amber-williams
app: water-tracker-app-client
name: water-tracker-app-client
component: website

inputs:
  src:
    src: ./src
    hook: cd .. && npm run build
    dist: ./../dist
```

**Comment by michaelwindell26** [comment]
I get this error when using a custom config file and npx.
`npx serverless --config serverless.dev.yml` = "service" property is missing in serverless.dev.yml

If i change my file back to `serverless.yml`
`npx serverless` = Success
