### ISSUE TITLE
Enable showing Framework Version w/ Components via `serverless -v`

### ISSUE THREAD

**Issue by ac360** [serverless/components#468]
Let's enable this again.

**Comment by eahefnawy** [comment]
just to be clear, if you're running `serverless -v` **in a components project**, you should see the components cli version, correct?

Another option is to add components to the versions list along with Enterprise and Platform SDK stuff.

**Comment by ac360** [comment]
Perhaps this is most helpful:

```
$ serverless -v

  Serverless Framework: 1.50.1
  Serverless Components CLI: 1.4.2
  Serverless Components Core: 1.3.9
  Serverless Dashboard Plugin: 2.3.1
  Serverless SDK: 3.2.1
```

**Comment by eahefnawy** [comment]
I've added it here:
https://github.com/serverless/serverless/pull/6702

**Comment by eahefnawy** [comment]
Done
https://github.com/serverless/serverless/pull/6702
