### ISSUE TITLE
website component doesn't seem to work with SPA (routing issue)

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#469]
From Josh Strange on Slack #help message:

@eslam Thank you for all your help on github! Could I trouble you/someone else with 1 more (no promises :laughing: ) question? My website was correctly deployed and available via cloudfront but it's a SPA and while it works fine if you visit the root and navigate around it doesn't work if you then refresh the page (after JS has pushed url state). I've seen this behavior before in SPA's in S3 buckets and wanted to know what the correct way to handle this was when using `@serverless/website`

**Comment by joshstrange** [comment]
By looking at https://medium.com/@P_Lessing/single-page-apps-on-aws-part-1-hosting-a-website-on-s3-3c9871f126 it looks like the way to fix this is via cloudfront setting it up so that if it 404's it returns a 200 and points at index.html. I can try digging a little bit into the code to see how easy this would be to implement

**Comment by eahefnawy** [comment]
@joshstrange I just pushed a fix. Could you try a redeploy?

**Comment by eahefnawy** [comment]
I've pushed the fix to the website component, so this would probably only work if you're NOT using a domain. I'll try to fix CloudFront too. Stand by...

**Comment by joshstrange** [comment]
@eahefnawy Just run `serverless` again? Can I ask where you pushed the fix? I'm interested in seeing how it was done but I don't see any new commits on [@serverless/website](https://github.com/serverless-components/website/commits/master)

**Comment by eahefnawy** [comment]
sorry, I mean I published to npm. Will push shortly

**Comment by joshstrange** [comment]
@eahefnawy Can confirm s3-website-us-east-1.amazonaws.com url now works as expected and that custom domain is not. I will say that just setting the error document to index.html will "sort of" work but it does still return a 404 to the client. The blog post I linked shows how to fix it in cloudfront but idk if you can do something similar in S3 buckets (mask 404's as 200's)

**Comment by eahefnawy** [comment]
Thanks @joshstrange ... doing that now...

**Comment by eahefnawy** [comment]
@joshstrange I just made that change. Could you try to redeploy?

**Comment by eahefnawy** [comment]
changes might take a while to reflect, but after deployment you could check your distribution error pages page to make sure the error page was created. Please let me know 😊

**Comment by joshstrange** [comment]
Deploying now, hot damn that was fast! I really appreciate your attention on this!

**Comment by joshstrange** [comment]
New permission time 😄 

````
cloudfront:GetDistributionConfig
````

Adding to my policy now

**Comment by eahefnawy** [comment]
haha 😅 

btw here are the changes since you're curious (love that!)

https://github.com/serverless-components/website
https://github.com/serverless-components/domain

**Comment by joshstrange** [comment]
@eahefnawy Still deploying (I'll post back when it's done) but I can see in CF that it is going to redirect the 404 -> index.html (200) so I think we are good 🙌. All of this serverless stuff is super exciting to work with and while I've spent a little over a week just getting stuff into place (and making plenty of mistakes or missteps) I feel like I'm finally ready to hit the ground running.

**Comment by joshstrange** [comment]
@eahefnawy Ok, it finished deploying but I'm still getting an error but it's not a 404: [https://www.foodweek.app/auth/login](https://www.foodweek.app/auth/login) <- Going to the root works fine but with the path throws the following error: 

````

<Error>
  <link type="text/css" id="dark-mode" rel="stylesheet" href=""/>
  <style type="text/css" id="dark-mode-custom-style"/>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>407CF8F06BB6D047</RequestId>
  <HostId>
FVWG25P/fOK76Z1/QEWRO5+s/xGNC7aQxBYW1BCrwm8QtM6QMDXeIBa53XBjriJignn28sG0qss=
  </HostId>
</Error>
````

**Comment by eahefnawy** [comment]
hmmm that's a tricky one. Let's see...

**Comment by eahefnawy** [comment]
@joshstrange I've added the 403 to the list of custom errors. Could you try a redeploy?

**Comment by joshstrange** [comment]
Trying now

**Comment by joshstrange** [comment]
`serverless` ran fine and I see the 403->index.html (200) in CF and my SPA works now! THANK YOU!

I literally could not have asked for a better response, from the co-founder no less! 😀 You rock!

**Comment by eahefnawy** [comment]
no sir, YOU rock! 😊 

Just keep the feedback coming, I'm always here...
