### ISSUE TITLE
ACM Certificate is taking a while error

### ISSUE THREAD

**Issue by tomeraz** [serverless/components#483]
Hi,
When running serverless command got this error three times at three different hours.
Any idea how to fix this?
```
Error: Your newly validated AWS ACM Certificate is taking a while to register as valid. 
Please try running this component again in a few minutes
```

**Comment by eahefnawy** [comment]
@tomeraz it's likely that your certificate did not validate. I'm guessing a DNS issue. Did you purchase your domain from Route53? or using an external registrar?

**Comment by tomeraz** [comment]
Transferred the domain from an external registrar.
How can I fix this issue?
I don't mind changing dns servers

**Comment by eahefnawy** [comment]
@tomeraz are you certain the domain/name servers transfer was completed? It seems that AWS don't have control over the DNS records to do the validation.

**Comment by tomeraz** [comment]
I think so, how can I make sure?

**Comment by eahefnawy** [comment]
do you see a CNAME record in Route53 with a long random `name` value?

**Comment by tomeraz** [comment]
there are no CNAME records

**Comment by eahefnawy** [comment]
hmmm 🤔 ... you're gonna have to do the validation manually. If you could go to AWS ACM and go to your domain certificate, then click on "Create Records in DNS" (it's hidden somewhere if I remember correctly). You should follow some simple steps to auto validate for you via DNS, which would create a long random CNAME for validation.

**Comment by tomeraz** [comment]
Thanks, that did it. ACM showed incomplete validation button to create route53 record.
Deployment was successful.
