### ISSUE TITLE
serverless components without npm

### ISSUE THREAD

**Issue by tomeraz** [serverless/components#484]
Is using npm a requirement to use serverless components?
Can I config components without npm?
```
  component: "@username/package"
```

**Comment by eahefnawy** [comment]
@tomeraz you can reference a local component that is not on npm with `component: ../path/to/dir/containing/serverless.js`. So you can build multipe components this way and push them together in a single repo.

Could you clarify why using npm is an issue for you?

**Comment by tomeraz** [comment]
Thank you 🙏
Not using npm because I'm building a commercial product, we don't have an
npm account and our code needs to be private.

**Comment by eahefnawy** [comment]
That makes sense 👍
