### ISSUE TITLE
Throw warning if credentials object is empty

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#495]
New AWS/Serverless users might not have AWS credentials setup in their machine, and they might not notice the `.env` documentations. They'd try to run a specific component, but AWS would return an unfriendly error.

For better DX, we should inform users that credentials are not found and they need to create a .env file.

**Comment by AbderrahimSoubaiElidrissi** [comment]
I will take this

**Comment by eahefnawy** [comment]
Thanks again for your contribution @AbderrahimSoubaiElidrissi 😊 

This issue is now irrelevant.
