### ISSUE TITLE
Run custom methods using YAML template

### ISSUE THREAD

**Issue by Pavel910** [serverless/components#497]
Currently we are unable to run `sls customMethod` on a YAML template. If I'm not mistaken, it could be implemented at [this here location](https://github.com/serverless/cli/blob/master/src/index.js#L205) in the CLI.

The reason this would be very useful to support is that, you could add components to your template and you would run the desired custom method, but only the components that have it implemented would execute. So out of 5 components in my template, maybe only 3 would have an `install` method defined. Does this make sense?

### Possible solution
I've tried implementing a possible solution, but I have a small problem: the CLI itself lacks the `load` function to load the component. Here is the relevant chunk of code:

```js
// If we are using the YAML template...
if (inputs.template) {
  // Find components
  const aliases = Object.keys(inputs.template).filter((key) => {
    return (
      typeof inputs.template[key] === 'object' && inputs.template[key].hasOwnProperty('component')
    )
  })

  for (let i = 0; i < aliases.length; i++) {
    const alias = aliases[i]
    // !! load component - this is the missing part !!
    const cmp = await load(inputs.template[alias].component)
    // If component contains the requested custom method, run it and store the output
    if(cmp[method]) {
        // Get alias inputs
        const cmpInputs = inputs.template[alias].inputs
        outputs[alias] = await cmp[method](cmpInputs)
    }
  }
} else if (typeof component[method] !== 'function') {
  throw Error(`  method ${method} not found`)
}
```

@eahefnawy does this look like it could work, even remotely? If yes, how should I go about the `load` function?

Looking forward to hearing your opinion on this :)

**Comment by eahefnawy** [comment]
Yeah we def need this functionality. I'm not sure this though:

> but only the components that have it implemented would execute. So out of 5 components in my template, maybe only 3 would have an install method defined. Does this make sense?

Do we wanna sort of "patch run" custom methods like we're doing with deploy/remove? 🤔 ... I was thinking more about specifying the key of the component you wanna target. So for this yaml:

```yml
myBucket
  component: "@serverless/aws-s3"

myLambda:
  component: "@serverless/aws-lambda"
```

You could run `serverless myBucket.upload` which would execute `upload` only on the `myBucket` component. @Pavel910 what you think of this experience? 🤔 ... I sort of dislike the `.` on the CLI though.

Regarding implementation, I think it might be better to have most of this logic in the [template component](https://github.com/serverless/template) since it's related only to the template. The CLI would just pass in the specified component alias (`myBucket`) and the custom method (`upload`).

Overall, I think the template component (regardless of the CLI) could benefit from this functionality

**Comment by Pavel910** [comment]
@eahefnawy I understand the risk of `patch running`, as you may not be aware of what some components might do in the process, but on the other hand, having a big `YAML` config with components taken from `npm` this can lead to a lot of manual per-component running.

I have a suggestion, which is borrowed from `lerna` (a monorepo management tool), here is an example:
```
// Run "lint" script on all packages that have it defined
lerna run lint

// Run "lint" script only on the selected packages (using --scope parameter)
lerna run --scope package-1 --scope *-2 lint
``` 

Maybe we could do something similar with `sls`:
```
sls install --component=myBucket --component=myLambda
```
This way we can support running a method on a single AND multiple components at once.

**Comment by eahefnawy** [comment]
> sls install --component=myBucket --component=myLambda

I like that!! I think that would be the best of both worlds!

@ac360 what you think about this?

**Comment by barrysteyn** [comment]
Version 1.1.12 @serverless/template breaks the example above. It seems to get this working, it would take some time reading source code and understanding things. Better if @Pavel910 could just adapt his example above to use the new template.
