### ISSUE TITLE
Add GraphQL API to the list of templates

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#498]

**Comment by francismarcus** [comment]
I'll gladly do this!
What component would you prefer to be used?

**Comment by ac360** [comment]
@francismarcus The new AppSync Component would be best.  Thanks!

**Comment by francismarcus** [comment]
Submitted a PR using the AppSync Component with .vtl templates to resolve data. 
However, I think it would be beneficial to have another gql template as well using resolvers.

I propose I add another template using the Backend or Lambda Component with Apollo.
Let me know

**Comment by eahefnawy** [comment]
Thanks @francismarcus ... I reviewed your PR and requested some changes. Another template with Lambda would be awesome. Could be in a different PR though 😊

**Comment by eahefnawy** [comment]
This issue should be fine 😊

**Comment by francismarcus** [comment]
What component would you prefer the other template to be made using? :)

**Comment by eahefnawy** [comment]
a template with aws-lambda would be ideal 😊
