### ISSUE TITLE
S3 Bucket - setting CORS

### ISSUE THREAD

**Issue by doitadrian** [serverless/components#500]
Hi,

I'm deploying a new bucket using the `@serverless/aws-s3` component, and I need to set its CORS configuration. I cannot find a way to set this via `inputs`. I believe this might be missing at the moment.

Would implementing this be something of your interest? I can jump on it, no problem.

**Comment by eahefnawy** [comment]
Thanks @doitadrian. That would be a nice addition. Feel free to send a PR here:
https://github.com/serverless-components/aws-s3

Please share how you'd like to implement this and how the inputs would look like. Would be great ifi it's non breaking as well.
