### ISSUE TITLE
@serverless/website - update AWS Bucket Policy

### ISSUE THREAD

**Issue by fasaas** [serverless/components#537]
When I deploy using `@serverless/website` I am unable to override the Bucket Policy for the S3 bucket I am creating.

Instead of it being:
```json
"Principal": {
    "AWS": "*"
}
```

I would like it to be configurable to achieve:
```json
"Principal": "*"
```

Is this achievable?
I would say yes since I installed the NPM package locally, and I was able to find the method `configureBucketForHosting` inside `utils.js`, the `Principal` value is hardcoded.

Is there a way for me to create a pull request to @serverless/website?
I am not able to find the open source repo

**Comment by medikoo** [comment]
> Is there a way for me to create a pull request to @serverless/website?
> I am not able to find the open source repo

Please move this request here: https://github.com/serverless-components/website
