### ISSUE TITLE
Access outputs of components after deployment

### ISSUE THREAD

**Issue by nguyen190887** [serverless/components#538]
I'm currently using `@serverless/aws-app-sync` for my project. After deploying the stack successfully, I would like to retrieve info like `GraphQlApiUrl`, `GraphQlApiKeyDefault` so that I can pass them to another build step (to bundle and deploy my website built with `GatsbyJS`). Is that feasible in `Serverless Components`? If yes, could you show me how to do this?

FYI - When I used [serverless-appsync-plugin](https://github.com/sid88in/serverless-appsync-plugin), I can easily grab these info by running `sls info -v` command.

One more question, where is state of resources stored in `Serverless Components`? I did take a look at Cloud Formation template and didn't see them. And in case the state is not stored in a centralized place, how can the team work together on this?

Many Thanks,
Tri

**Comment by medikoo** [comment]
@nguyen190887 thanks for request. Can you move this issue to https://github.com/serverless-components/aws-app-sync ? I believe it belongs there

**Comment by nguyen190887** [comment]
Thanks @medikoo for quick response. I created another ticket in `aws-app-sync` component repo (https://github.com/serverless-components/aws-app-sync/issues/20).

How about below concern? Could you help with?
>One more question, where is state of resources stored in Serverless Components? I did take a look at Cloud Formation template and didn't see them. And in case the state is not stored in a centralized place, how can the team work together on this?

**Comment by medikoo** [comment]
> One more question, where is state of resources stored in Serverless Components?

Currently it is stored locally in `.serverless` folder of a project.

Remote state storage (which will allow centralized stage support) will be supported soon. Track https://github.com/serverless/components/issues/475 for status on that

**Comment by nguyen190887** [comment]
I did have a look at the `.serverless` folder, but looks like state of `components` (in my case, it's `aws-app-sync`) is not there.

My `.serverless` folder looks like below and I think it must be in `serverless-state.json`, but it's not.
![image](https://user-images.githubusercontent.com/5491571/70670218-06f61f80-1cab-11ea-86a8-3f53e7c00dc5.png)

I guess this is because we are using AWS CLI to manipulate component related resources (not treat them as a part of CloudFormation's stack). Is that correct? And if yes, do you know where are these resources are stored?

**Comment by medikoo** [comment]
Content of a folder suggests you're not using serverless components but [serverless v1](https://github.com/serverless/serverless/)

**Comment by nguyen190887** [comment]
Oops... I was not aware of this. Thank you for letting me know 😄 

Let me figure out how to make this work with my current code. FYI - I'm mixing both `functions` and `serverless components` in the same `serverless.yml`.
