### ISSUE TITLE
White text is still used frequently, but causes issues on white terminals

### ISSUE THREAD

**Issue by ac360** [serverless/components#576]
The CLI utils is still using the white color in multiple areas and this is barely readable on terminals with white backgrounds.  All white coloring should be removed and no color (i.e. default color) should be specified.

**Comment by eahefnawy** [comment]
I've already switched white to the default color. Could you point me to where exactly you're referring to in the CLI utils? 🤔 

It looks fine on my white terminal
<img width="571" alt="Screen Shot 2020-04-06 at 3 52 22 PM" src="https://user-images.githubusercontent.com/2312463/78560432-bfc60880-781e-11ea-90cd-a5fa3d3c0b43.png">

**Comment by eahefnawy** [comment]
Maybe you're referring to the `white` variable that we have all over the place? The value of this variable is the default color though. You can see that commented here:

https://github.com/serverless/components/blob/master/src/cli/CLI.js#L15
