### ISSUE TITLE
Private components

### ISSUE THREAD

**Issue by hypexr** [serverless/components#591]
What's the preferred way to create and publish private components?

**Comment by ac360** [comment]
@hypexr This isn't available yet.  We think it should be pretty straightforward.  `private: true` in `serverless.component.yml`. 

What would you like to see here?

**Comment by hypexr** [comment]
@ac360 I've done some more experimenting and found that the current functionality supports my use cases: 

1. Use a custom component that published to a private npm repository
2. Use a custom component that's in a git repository
3. Use a local component

I forked aws-lambda and used that for experimentation.

For #1 (private npm registry) I published to my private repository `@company/aws-lambda`.  I specified `component: "@company/aws-lambda"` in `serverless.yml` and it downloaded to `~/.servereless/components/registry` and used this version.

For #2 (git repo) I was able to add an entry like `"aws-lambda-custom": "git+https://github.com/hypexr/aws-lambda.git#srv3",` to dependencies.  Giving it a different name than the existing component published to the serverless registry allowed `component: "aws-lambda-custom"` in `serverless.yml` to find and use the correct one.

For #3 (local) I set `component: "../aws-lambda"` and it successfully used the code in the local directory.

I imagine that this could be streamlined with a flag like `private: true`.

Maybe it would be good to document the options above for users with similar use cases?
 
Framework Core: 1.67.0
Plugin: 3.6.1
SDK: 2.3.0
Components: 2.22.3

**Comment by ac360** [comment]
@hypexr Ok.  Please note that we've just released Serverless Components GA which does not use NPM and instead has its own registry for Components - https://www.youtube.com/watch?v=3ndGjkuqyyc

We'll be revisiting the private registry concept again soon here.  There is little work needed to support that with the new model of Serverless Components.  The BETA version of Components will continue to work as is (which you are using).
