### ISSUE TITLE
Incorrect serverless.yml config structure

### ISSUE THREAD

**Issue by g-wozniak** [serverless/components#594]
Currently in the [serverless.yml](https://github.com/serverless/components/blob/master/templates/website/serverless.yml) file the structure is:

src:
    src: ./src
    hook: npm run build
    dist: ./dist

Should `dist` and other properties be nested inside `src` ?
Also, documentation here https://github.com/serverless-components/website presents different structure of the yml file.

Please close if the above is intentional, but would be great to know where from the inconsistency is coming, to better understand the component.

**Comment by eahefnawy** [comment]
@g-wozniak you could provide your source code in two ways:

The easy way:

```yml
inputs:
  src: ./src
```

Or the advanced way, which allows for running hooks (such as builders) before packaging

```yml
inputs:
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
```
So both are correct.
