### ISSUE TITLE
`serverless deploy --all` does not work w/ `inputs.src.dist`

### ISSUE THREAD

**Issue by ac360** [serverless/components#611]
# Description

When running `serverless deploy --all` w/ a project that uses `inputs.src.dist`, an error will be thrown due to how that command modifies the paths.

You can recreate this by running the Website Component, which has a build process.

**Comment by hkbarton** [comment]
@ac360 @eahefnawy I think this should be already fixed in `platform-client-china` or in `commands-cn`, I'll see if I can pull the fix over here

**Comment by eahefnawy** [comment]
Thanks @hkbarton 😊

**Comment by eahefnawy** [comment]
Just PRed a fix in #613 ... @hkbarton could you review?

**Comment by hkbarton** [comment]
@eahefnawy done! thanks for the quick fix!

**Comment by eahefnawy** [comment]
Fixed
