### ISSUE TITLE
Unexpected 'core-js@2' dependency

### ISSUE THREAD

**Issue by medikoo** [serverless/components#620]
Regression introduced with https://github.com/serverless/components/pull/608

There are various issues with `core-js`.
- It list an advertisment on install. So currently when someone installs `npm install -g serverless` it sees: ![Screenshot 2020-05-04 at 12 35 10](https://user-images.githubusercontent.com/122434/80957601-c5a21000-8e03-11ea-82bd-4981463714fc.png)
- There are other issues related to `postinstall` script: https://github.com/serverless/serverless/issues/7654
- It weights 7MB, which makes it 6th largest dependency of Serverless Framework, and that significantly contributes to general size of a project and its standalone binary

**Comment by hkbarton** [comment]
will look into this ASAP

**Comment by hkbarton** [comment]
the issue is now fixed
