### ISSUE TITLE
Issue with runningTemplate in nested project

### ISSUE THREAD

**Issue by MLSTRM** [serverless/components#623]
# Description
Serverless invocation fails when running serverless process from a folder which contains subdirectories which contain serverless.yml files with cloudformation functions within them. The specific error which occurs is:

`"The serverless.yml file has icorrect format. Details: unknown tag !<!GetAtt> in ..." `
(also minor note around the spelling of the error)

The process fails from within runningTemplate, due to use of loadInstanceConfig as opposed to the legacyLoadInstanceConfig, which appears to rethrow any parsing exceptions rather than swallowing them.

This has begun appearing on builds due to the core serverless library using a lower bounded dependency, so the newest version of components containing the offending change was automatically included on recent changes.

## Additional Data
Specific line of code

https://github.com/serverless/components/blob/master/src/cli/utils.js#L465

The project structure I'm working from contains multiple serverless configurations in separated directories, upon attempting to invoke a serverless deploy from a folder which does not contain itself a serverless configuration file (e.g. using cd within the build process rather than the --config flag), the template lookup code runs against all subfolders, which then contain the aws provider specific yaml files. 
It potentially could be argued that the template resolution should occur from the location specified by the --config flag rather than the root process.cwd() location, which would also resolve the issue in my specific case, but not the more general one.

**Comment by medikoo** [comment]
@MLSTRM great thanks for reporting, we'll post a fix shortly
