### ISSUE TITLE
SERVERLESS_ACCESS_TOKEN Not supported yet?

### ISSUE THREAD

**Issue by rrooding** [serverless/components#627]
The readme writes:

> Further, your Component Instances can easily be deployed with CI/CD, as long as you make sure to include a SERVERLESS_ACCESS_TOKEN environment variable.

But when I set this variable, I still get an error about not being logged in. What is the status for this?

**Comment by rrooding** [comment]
I've found this in the old docs: https://www.serverless.com/framework/docs/dashboard/cicd/running-in-your-own-cicd/

`SERVERLESS_ACCESS_KEY: Your Serverless Framework Dashboard access token from previous step.`

And that works, is the readme incorrect or are you going to rename the variable?

**Comment by astuyve** [comment]
The readme is incorrect, sorry for the delay. Fixing shortly.
