### ISSUE TITLE
`--help` doesn't work

### ISSUE THREAD

**Issue by timsuchanek** [serverless/components#686]
When running `sls --help`, I don't get the help string.
I also tried `-h` and `help`, all of them don't give me any help string.

**Comment by medikoo** [comment]
@eahefnawy @ac360 I remember this being reported few times already.

`command --help` is what typically CLI user runs when searching for some documentation of a CLI

**Comment by eahefnawy** [comment]
@timsuchanek this is no longer an issue. We've added help for components. Thanks for reminding us about this! 👌
