### ISSUE TITLE
[Question] Non open-sourced depedencies

### ISSUE THREAD

**Issue by araujoigor** [serverless/components#700]
This is a question regarding the nature of the licensing and availability of the source code of a few dependencies of the serverless project. The question is being put here because the dependencies I couldn't find a corresponding repository exist in this project.

Since the serverless project is advertised as being an open-source project on its website, I got surprised, while browsing through the dependencies, to find a few that are not accessible on Github.

The dependencies I couldn't find on GitHub are (although licensed as ISC):

* @serverless/platform-client
* @serverless/platform-client-china

I assume these packages are specific to dealing with the Serverless Cloud platform (the paid service) and thus, "closed-sourced". Moreover, the distributed code (through NPM) is fully readable and well documented.

Still, I would like to check if there are any specific reasons for these two packages to not be available on GitHub.

Thanks!

**Comment by eahefnawy** [comment]
These two packages are not really closed source as we are aware they are publically available on NPM. They're just hosted in a private repo along with other private code for convenience since they're tightly coupled with backend changes.

**Comment by araujoigor** [comment]
Thanks for the answer, @eahefnawy. It makes sense. Closing it.
