### ISSUE TITLE
Where do components run?

### ISSUE THREAD

**Issue by Gaelan** [serverless/components#722]
The readme states this:

> One of the most important things to note is that Serverless Components only run in the cloud and do not run locally.

That's pretty vague and somewhat alarming. Where *are* the components running? Are they running on your servers? If so, does this mean we're trusting you with our code, AWS credentials, etc? What happens if you go out of business or stop offering this service for free?

None of those are inherently deal-breaking, but choosing an open-source library and choosing a SaaS product have very distinct considerations, and it would be great if the docs were more clear about which one was happening here.

**Comment by ac360** [comment]
Hi @Gaelan,

You're right.  We've built a cloud engine capable of blazing fast deployments and so much more, but we haven't documented this well enough yet, especially to address the concerns you raised.  To be honest, we just haven't gotten to it yet.  Our website still points to the Components beta project for example (which keeps me up at night).  We should be improving our communication in this area over the next few weeks.  Until then, our apologies, we're still a small team.
