### ISSUE TITLE
Serverless init error: Serverless command "init" not found

### ISSUE THREAD

**Issue by ljdatasci** [serverless/components#747]
# Description
Deploying an Express.js app from the dashboard does not work.  The command "serverless init sf_TdDXxC6H" produces the error "Serverless command "init" not found. Did you mean "info"? Run "serverless help" for a list of all available commands."

 
## Additional Data
Steps to reproduce:
1.  Login to Serverless.com
2. Click Create App
3. Select the Express.js template
4. Enter app name.
5. Run the install command

E.g. stack trace, version, operating system, ...
 Serverless Error ---------------------------------------

  Serverless command "init" not found. Did you mean "info"? Run "serverless help" for a list of all available commands.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.3

**Comment by ljdatasci** [comment]
I installed @serverless/core and was able to run the command.  Running npm i serverless did not install severless init or @serverless/core.  Should they be install along with the main Serverless library?

**Comment by astuyve** [comment]
@ljdatasci running `npm i -g serverless` will automatically fetch the latest version of this library, which includes `init` functionality. Can you try running `npm uninstall -g serverless` and retrying? The framework version in this output is quite old, with `1.78.1` being the latest release

**Comment by ljdatasci** [comment]
That fixed it.
