### ISSUE TITLE
serverless.yml env values not available during hook

### ISSUE THREAD

**Issue by zackdotcomputer** [serverless/components#806]
# Description

Right now it appears that during the execution of the `hook` for a component, the values set in `env` are not configured into the environment. They are, instead, only set during the execution of the component (when the component involves an eventual execution).

This is fine for components who use the env variables at runtime only, but for components like the `website` component where you likely want to use these values during *build* time it presents an issue.

## Current workaround

Currently the workaround for those using a node-based hook is to assign the env variables in the hook's command like this:
```
hook: REACT_APP_API_URL=some-value npm run build
```

However, this doesn't appear to dynamically update for `${output:...}` values in the serverless.

## Desired solution

To me the ideal solution would be to set the values of the serverless.yml `env` key into the environment in which the hook is executed. This would be a more graceful way to allow the insertion of complex env state to the hook's execution - especially for components where that execution is the only runtime event in the component's lifecycle.

At minimum, it would be nice if the replacement of serverless `${...}` variables actually worked in the hook. Currently, using one will evaluate as `""` but display on the dashboard as if it was populated.

**Comment by eahefnawy** [comment]
That makes a lot of sense. It's exactly how I think about it. In fact, I already opened a PR for that internally, just hasn't been merged yet.

**Comment by eahefnawy** [comment]
We merged a fix for this here https://github.com/serverlessinc/platform/pull/47
