### ISSUE TITLE
Stage option not working in CLI

### ISSUE THREAD

**Issue by jeremygottfried** [serverless/components#843]
Components don't support the CLI stage option. When I follow the directions in the README, it sets stage to "dev", no matter what I pass in the cli.

https://github.com/serverless/components#variables-stage

I'm using serverless v2.22.3, with the website component.

**Comment by mwawrusch** [comment]
I have the same problem with the lambda component. Given how critical this is I don't understand that it's not even commented on by team.

**Comment by mwawrusch** [comment]
This has been fixed in the latest release.
