### ISSUE TITLE
Invalid domain name identifier specified

### ISSUE THREAD

**Issue by nectarcode** [serverless/components#856]
# Description
I was able to initially deploy to api.mydomain.com with no issue, but then I tried changing the name in the yml and the domain name to be devapi.mydomain.com and then I started running into issues.

I tried deploying a name that was not valid and now it seems no matter what I do, I cannot run the `sls remove` command. I've tried every combination of domain name that I used. It will let me delete it in the dashboard but still tells me I need to run the `sls remove` command locally.

## Additional Data

Windows 10
sls components version 3.4.3

**Comment by nectarcode** [comment]
If I rename `name:` and remove @dev from the component name, it is working for me...but I'm still wondering how to remove that resource that I don't need there anymore.

**Comment by mwawrusch** [comment]
I am having the same problem with a resource stuck in the components dashboard. It's not possible to remove it there either (using the context menu)

**Comment by eahefnawy** [comment]
@nectarcode what are the errors that come up? And what component are you running?

**Comment by nectarcode** [comment]
Just the error in the title was the only one that came up. I believe it was using either the express or typescript component. I was able to resolve by deleting the existing stacks and redoing my AWS certificate to use the specific subdomains I wanted instead of using the wildcard.
