### ISSUE TITLE
Unable to view logs using serverless dev --debug command

### ISSUE THREAD

**Issue by nectarcode** [serverless/components#857]
# Description

I am trying to view console.log statements in my code using `sls dev --debug`
I am able to see the transaction log, but not able to see the console.log statements within my endpoint. Is there a different flag I need to set or am I missing something else?

## Additional Data

Windows 10
sls components 3.4.3

**Comment by eahefnawy** [comment]
@nectarcode seems to be working on my end. What component are you using? And could you provide code snippets just to make sure everything is plugged in as it should?

**Comment by nectarcode** [comment]
Tried on a different machine and the logs were showing up for me consistently.
