### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by nectarcode** [serverless/components#858]
# Description

Every endpoint I'm hitting after a successful deploy is returning Invalid or unexpected token, even /test... hitting /ping returns Healthy Connection though. I've edited very little from the fullstack template so I'm not sure why it's doing this, and I've had successful deploys previously, and been able to hit some endpoints that I added, ie: /v1/ping

I can see my transaction logs, but no other information or insight is provided. Any suggestions on how to proceed?

## Additional Data

Windows 10
sls components 3.4.3

**Comment by nectarcode** [comment]
I tried redeploying and I'm not getting a `message: Forbidden` response

**Comment by eahefnawy** [comment]
@nectarcode how consistent is that? What happens if you remove then deploy again?

Also, I'm guessing this only happens for the express endpoints? not website?

**Comment by nectarcode** [comment]
Not sure what the issue was but I couldn't replicate it on a different machine.
