### ISSUE TITLE
"service" property is missing in serverless.yml

### ISSUE THREAD

**Issue by gjgd** [serverless/components#860]
# Description

I have a multi stage setup, here is my current directory structure

```bash
➜ tree
.
├── README.md
├── package.json
└── serverless-config
    ├── dev
    │   └── serverless.yml
    └── prod
        └── serverless.yml

3 directories, 4 files
```

When I run `sls deploy --config=serverless-config/dev/serverless.yml --stage=dev` I get the following error
```
  Serverless Error ---------------------------------------
 
  "service" property is missing in serverless.yml
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.3
     Framework Version:         1.83.0
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
 

 
```

However, if I remove the prod directory and run the same command
```
➜ tree              
.
├── README.md
├── package.json
└── serverless-config
    └── dev
        └── serverless.yml
```
or if I flatten the directory structure (remove serverless-config) and run `sls deploy --config=dev/serverless.yml --stage=dev`
```
➜ tree
.
├── README.md
├── dev
│   └── serverless.yml
├── package.json
├── prod
    └── serverless.yml
```

then the deploy command is successful

Hence I think that there is a bug. Even though I specify the full path to the dev config, somehow the prod config interferes when they share a `serverless-config` directory

**Comment by eahefnawy** [comment]
I don't think there's a `--config` flag in the components CLI. I've shared more thoughts in #861

**Comment by gjgd** [comment]
Closing in favor of #861
