### ISSUE TITLE
Specifying non-AWS Credentials

### ISSUE THREAD

**Issue by james-a-roland** [serverless/components#870]
# Description
I created a new project via `sls init react-starter`, logged in via `sls login` and have a .env file in the root directory with my TENCENT_SECRET_ID and TENCENT_SECRET_KEY. However, it appears to still be looking for AWS credentials. Am I missing something obvious here or is there another way I can specify the credentials to use Tencent for login?

I found this repo just after looking at the [Tencent Docs](https://intl.cloud.tencent.com/document/product/1040/33164) and am completely new to serverless - apologies if it's a stupid question!

E.g. stack trace, version, operating system, ...
```
➜  react-starter sls info               

serverless ⚡framework
Action: "info" - Stage: "dev" - Org: "xxxx" - App: "react-starter" - Name: "react-starter"

Last Action:  deploy (8 minutes ago)
Deployments:  2
Status:       error
Component:    website@1.1.1

Error: AWS credentials not found. Make sure you have a .env file in the cwd. - Docs: https://git.io/JvArp
    at getClients (/var/task/utils.js:25:11)
    at Website.deploy (/var/task/serverless.js:29:21)
    at Runtime.module.exports [as handler] (/opt/nodejs/node_modules/@serverless/core/handler.js:331:53)

Outputs:


Serverless › Success


Full details: https://app.serverless.com/jamesakira/apps/react-starter/react-starter/dev

Serverless › App info fetched

➜  react-starter cat .env               
# Learn more about about the credentials needed
# to deploy your app https://github.com/serverless/components#credentials

TENCENT_SECRET_ID=xxxxx
TENCENT_SECRET_KEY=xxxxxx
➜  react-starter sls deploy             

serverless ⚡framework
Action: "deploy" - Stage: "dev" - Org: "xxx" - App: "react-starter" - Name: "react-starter"

5s › Serverless › AWS credentials not found. Make sure you have a .env file in the cwd. - Docs: https://git.io/JvArp 

  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 

```

**Comment by eahefnawy** [comment]
@james-a-roland It seems that you're trying to use Tencent Cloud, are you located in China?

**Comment by timqian** [comment]
To use Tencent Cloud outside China, you have to add this setting into your .env file or environment varialbe
```
SERVERLESS_PLATFORM_VENDOR=tencent
```

**Comment by james-a-roland** [comment]
> @james-a-roland It seems that you're trying to use Tencent Cloud, are you located in China?

I'm not currently located in China, but was just trying to learn more about Tencent's Platform for my own knowledge.

> To use Tencent Cloud outside China, you have to add this setting into your .env file or environment varialbe
> 
> ```
> SERVERLESS_PLATFORM_VENDOR=tencent
> ```

That worked - thank you!
