### ISSUE TITLE
This Component requires an “AWS” Provider. Click the following link to configure credentials for that Provider

### ISSUE THREAD

**Issue by gadielkalleb** [serverless/components#892]
# Description
deploy worked until last week, now it presents this message

I don't know what it can be these are the evidences that I have here on my machine

```
Action: "deploy" - Stage: "dev" - Org: "gadielkalleb" - App: "sls-espaco-inovacao-1" - Name: "sls-espaco-inovacao-1"

21s › Serverless › This Component requires an “AWS” Provider. Click the following link to configure credentials for that Provider: 

  https://app.serverless.com/gadielkalleb/settings/providers?providerId=new&provider=aws 

  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 

```
## evidencies
ok inside the dashboard I have the credential registered

![Captura de tela de 2021-02-16 11-31-45 21](https://user-images.githubusercontent.com/25777532/108077055-dfd37480-704a-11eb-8aae-347df1d87487.png)

![Captura de tela de 2021-02-16 11-41-01](https://user-images.githubusercontent.com/25777532/108077999-e9a9a780-704b-11eb-8154-168191087cbd.png)

serverless version
```
Framework Core: 2.23.0
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.0
```

my serverless.yml file

![Captura de tela de 2021-02-16 11-37-23](https://user-images.githubusercontent.com/25777532/108077554-67b97e80-704b-11eb-9b7b-aabe69a622e1.png)

project struct

![Captura de tela de 2021-02-16 11-38-37](https://user-images.githubusercontent.com/25777532/108077723-99324a00-704b-11eb-9db2-f6501fb1973a.png)

**Comment by Cameron-C-Chapman** [comment]
@gadielkalleb I had the same issue and was able to resolve it by explicitly adding that provider to the service in the dashboard ui. In your screen shot where it shows your default provider listed, if the "Add Provider" button is red and not grey/disabled that means the listed provider hasn't actually been added. 

It seems like it's added since it's listed, but you have to click the Add Provider button and select that provider to assign it to the service.

**Comment by gadielkalleb** [comment]
@Cameron-C-Chapman you are right! that's right, thanks

**Comment by ration** [comment]
This is also the error if the role based AWS provider configuration doesn't work.
