### ISSUE TITLE
TypeError: Cannot read property 'ping' of null

### ISSUE THREAD

**Issue by simsketch** [serverless/components#925]
Using the latest express component, trying to run

`sls dev`

but it does not succeed because of this error.

```
C:\Users\Me\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\platform-client\src\Connection.js:112
          this.connection.ping();
                          ^
TypeError: Cannot read property 'ping' of null
    at Timeout._onTimeout (C:\Users\Me\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\platform-client\src\Connection.js:112:27)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

I've used this command successfully in the past, so I'm not sure what changed.

**Comment by nectarcode** [comment]
I didn't change anything, but it is working now...I'm guessing it was on their end. ¯\_(ツ)_/¯

**Comment by simsketch** [comment]
It's working now...I didn't change anything, so I'm guessing it was on their end. `¯\_(ツ)_/¯`
